apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: python-pv-pvc
spec:
  entrypoint: write-files
  templates:
    - name: write-files
      container:
        image: nitinsuvagia/python-pv:latest  # Replace with your Docker image name
        command: [python, /usr/src/app/write_files.py]
        volumeMounts:
          - name: pv-storage
            mountPath: /mnt/pv-data
      volumes:
        - name: pv-storage
          persistentVolumeClaim:
            claimName: example-pvc
